package model.BO.AM;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 26 12:46:55 EEST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpByEmailImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpByEmailImpl() {
    }
}

